kind: BuildConfig
apiVersion: v1
metadata:
  name: mars-rover-photos
spec:
  output:
    to:
      kind: DockerImage
      name: quay.io/ecwpz91/mrp:latest
  source:
    # Expect a local directory to be streamed to OpenShift as a build source
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in ./Dockerfile
      dockerfilePath: Dockerfile