kind: BuildConfig
apiVersion: v1
metadata:
  name: mars-rover-photos-pipeline
spec:
  source:
    git:
      uri: "https://github.com/ecwpz91/mrp.git"
      ref: main
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile